services:
  - type: web
    name: eletrostartbackend-api
    env: node
    region: oregon
    rootDir: server
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: node dist/index.js
    envVarGroups: []
    autoDeploy: true
