services:
  - type: web
    name: eletrostartbackend-api
    runtime: node
    rootDir: server
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: node dist/index.js
    autoDeploy: true
